/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandlordsRouteImport } from './routes/landlords'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSavedRouteImport } from './routes/_authenticated/app.saved'
import { Route as AuthenticatedAppRequestsRouteImport } from './routes/_authenticated/app.requests'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app.payments'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppLandlordRouteImport } from './routes/_authenticated/app.landlord'
import { Route as AuthenticatedAppExploreRouteImport } from './routes/_authenticated/app.explore'
import { Route as AuthenticatedAppContractsRouteImport } from './routes/_authenticated/app.contracts'
import { Route as AuthenticatedAppBecomeLandlordRouteImport } from './routes/_authenticated/app.become-landlord'
import { Route as AuthenticatedAppTenantDashboardRouteImport } from './routes/_authenticated/app.tenant.dashboard'
import { Route as AuthenticatedAppPropertyIdRouteImport } from './routes/_authenticated/app.property.$id'
import { Route as AuthenticatedAppLandlordPropertiesRouteImport } from './routes/_authenticated/app.landlord.properties'
import { Route as AuthenticatedAppLandlordOnboardingRouteImport } from './routes/_authenticated/app.landlord.onboarding'
import { Route as AuthenticatedAppContractsIdRouteImport } from './routes/_authenticated/app.contracts.$id'
import { Route as AuthenticatedAppLandlordUnitsIdRouteImport } from './routes/_authenticated/app.landlord.units.$id'
import { Route as AuthenticatedAppLandlordPropertiesNewRouteImport } from './routes/_authenticated/app.landlord.properties.new'
import { Route as AuthenticatedAppLandlordPropertiesIdRouteImport } from './routes/_authenticated/app.landlord.properties.$id'
import { Route as AuthenticatedAppLandlordPropertiesIdUnitsRouteImport } from './routes/_authenticated/app.landlord.properties.$id.units'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordsRoute = LandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSavedRoute = AuthenticatedAppSavedRouteImport.update({
  id: '/app/saved',
  path: '/app/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRequestsRoute =
  AuthenticatedAppRequestsRouteImport.update({
    id: '/app/requests',
    path: '/app/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/app/payments',
    path: '/app/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/app/messages',
    path: '/app/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppLandlordRoute =
  AuthenticatedAppLandlordRouteImport.update({
    id: '/app/landlord',
    path: '/app/landlord',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppExploreRoute = AuthenticatedAppExploreRouteImport.update({
  id: '/app/explore',
  path: '/app/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppContractsRoute =
  AuthenticatedAppContractsRouteImport.update({
    id: '/app/contracts',
    path: '/app/contracts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBecomeLandlordRoute =
  AuthenticatedAppBecomeLandlordRouteImport.update({
    id: '/app/become-landlord',
    path: '/app/become-landlord',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppTenantDashboardRoute =
  AuthenticatedAppTenantDashboardRouteImport.update({
    id: '/app/tenant/dashboard',
    path: '/app/tenant/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPropertyIdRoute =
  AuthenticatedAppPropertyIdRouteImport.update({
    id: '/app/property/$id',
    path: '/app/property/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppLandlordPropertiesRoute =
  AuthenticatedAppLandlordPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppLandlordRoute,
  } as any)
const AuthenticatedAppLandlordOnboardingRoute =
  AuthenticatedAppLandlordOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppLandlordRoute,
  } as any)
const AuthenticatedAppContractsIdRoute =
  AuthenticatedAppContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppContractsRoute,
  } as any)
const AuthenticatedAppLandlordUnitsIdRoute =
  AuthenticatedAppLandlordUnitsIdRouteImport.update({
    id: '/units/$id',
    path: '/units/$id',
    getParentRoute: () => AuthenticatedAppLandlordRoute,
  } as any)
const AuthenticatedAppLandlordPropertiesNewRoute =
  AuthenticatedAppLandlordPropertiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppLandlordPropertiesRoute,
  } as any)
const AuthenticatedAppLandlordPropertiesIdRoute =
  AuthenticatedAppLandlordPropertiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppLandlordPropertiesRoute,
  } as any)
const AuthenticatedAppLandlordPropertiesIdUnitsRoute =
  AuthenticatedAppLandlordPropertiesIdUnitsRouteImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AuthenticatedAppLandlordPropertiesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/tenants': typeof TenantsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/become-landlord': typeof AuthenticatedAppBecomeLandlordRoute
  '/app/contracts': typeof AuthenticatedAppContractsRouteWithChildren
  '/app/explore': typeof AuthenticatedAppExploreRoute
  '/app/landlord': typeof AuthenticatedAppLandlordRouteWithChildren
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/requests': typeof AuthenticatedAppRequestsRoute
  '/app/saved': typeof AuthenticatedAppSavedRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/contracts/$id': typeof AuthenticatedAppContractsIdRoute
  '/app/landlord/onboarding': typeof AuthenticatedAppLandlordOnboardingRoute
  '/app/landlord/properties': typeof AuthenticatedAppLandlordPropertiesRouteWithChildren
  '/app/property/$id': typeof AuthenticatedAppPropertyIdRoute
  '/app/tenant/dashboard': typeof AuthenticatedAppTenantDashboardRoute
  '/app/landlord/properties/$id': typeof AuthenticatedAppLandlordPropertiesIdRouteWithChildren
  '/app/landlord/properties/new': typeof AuthenticatedAppLandlordPropertiesNewRoute
  '/app/landlord/units/$id': typeof AuthenticatedAppLandlordUnitsIdRoute
  '/app/landlord/properties/$id/units': typeof AuthenticatedAppLandlordPropertiesIdUnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/tenants': typeof TenantsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/become-landlord': typeof AuthenticatedAppBecomeLandlordRoute
  '/app/contracts': typeof AuthenticatedAppContractsRouteWithChildren
  '/app/explore': typeof AuthenticatedAppExploreRoute
  '/app/landlord': typeof AuthenticatedAppLandlordRouteWithChildren
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/requests': typeof AuthenticatedAppRequestsRoute
  '/app/saved': typeof AuthenticatedAppSavedRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/contracts/$id': typeof AuthenticatedAppContractsIdRoute
  '/app/landlord/onboarding': typeof AuthenticatedAppLandlordOnboardingRoute
  '/app/landlord/properties': typeof AuthenticatedAppLandlordPropertiesRouteWithChildren
  '/app/property/$id': typeof AuthenticatedAppPropertyIdRoute
  '/app/tenant/dashboard': typeof AuthenticatedAppTenantDashboardRoute
  '/app/landlord/properties/$id': typeof AuthenticatedAppLandlordPropertiesIdRouteWithChildren
  '/app/landlord/properties/new': typeof AuthenticatedAppLandlordPropertiesNewRoute
  '/app/landlord/units/$id': typeof AuthenticatedAppLandlordUnitsIdRoute
  '/app/landlord/properties/$id/units': typeof AuthenticatedAppLandlordPropertiesIdUnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/landlords': typeof LandlordsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/tenants': typeof TenantsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/app/become-landlord': typeof AuthenticatedAppBecomeLandlordRoute
  '/_authenticated/app/contracts': typeof AuthenticatedAppContractsRouteWithChildren
  '/_authenticated/app/explore': typeof AuthenticatedAppExploreRoute
  '/_authenticated/app/landlord': typeof AuthenticatedAppLandlordRouteWithChildren
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/requests': typeof AuthenticatedAppRequestsRoute
  '/_authenticated/app/saved': typeof AuthenticatedAppSavedRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/contracts/$id': typeof AuthenticatedAppContractsIdRoute
  '/_authenticated/app/landlord/onboarding': typeof AuthenticatedAppLandlordOnboardingRoute
  '/_authenticated/app/landlord/properties': typeof AuthenticatedAppLandlordPropertiesRouteWithChildren
  '/_authenticated/app/property/$id': typeof AuthenticatedAppPropertyIdRoute
  '/_authenticated/app/tenant/dashboard': typeof AuthenticatedAppTenantDashboardRoute
  '/_authenticated/app/landlord/properties/$id': typeof AuthenticatedAppLandlordPropertiesIdRouteWithChildren
  '/_authenticated/app/landlord/properties/new': typeof AuthenticatedAppLandlordPropertiesNewRoute
  '/_authenticated/app/landlord/units/$id': typeof AuthenticatedAppLandlordUnitsIdRoute
  '/_authenticated/app/landlord/properties/$id/units': typeof AuthenticatedAppLandlordPropertiesIdUnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/explore'
    | '/forgot-password'
    | '/help'
    | '/landlords'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/safety'
    | '/tenants'
    | '/terms'
    | '/verify-email'
    | '/auth/callback'
    | '/app/become-landlord'
    | '/app/contracts'
    | '/app/explore'
    | '/app/landlord'
    | '/app/messages'
    | '/app/payments'
    | '/app/profile'
    | '/app/requests'
    | '/app/saved'
    | '/app/'
    | '/app/contracts/$id'
    | '/app/landlord/onboarding'
    | '/app/landlord/properties'
    | '/app/property/$id'
    | '/app/tenant/dashboard'
    | '/app/landlord/properties/$id'
    | '/app/landlord/properties/new'
    | '/app/landlord/units/$id'
    | '/app/landlord/properties/$id/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/explore'
    | '/forgot-password'
    | '/help'
    | '/landlords'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/safety'
    | '/tenants'
    | '/terms'
    | '/verify-email'
    | '/auth/callback'
    | '/app/become-landlord'
    | '/app/contracts'
    | '/app/explore'
    | '/app/landlord'
    | '/app/messages'
    | '/app/payments'
    | '/app/profile'
    | '/app/requests'
    | '/app/saved'
    | '/app'
    | '/app/contracts/$id'
    | '/app/landlord/onboarding'
    | '/app/landlord/properties'
    | '/app/property/$id'
    | '/app/tenant/dashboard'
    | '/app/landlord/properties/$id'
    | '/app/landlord/properties/new'
    | '/app/landlord/units/$id'
    | '/app/landlord/properties/$id/units'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/explore'
    | '/forgot-password'
    | '/help'
    | '/landlords'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/safety'
    | '/tenants'
    | '/terms'
    | '/verify-email'
    | '/auth/callback'
    | '/_authenticated/app/become-landlord'
    | '/_authenticated/app/contracts'
    | '/_authenticated/app/explore'
    | '/_authenticated/app/landlord'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/requests'
    | '/_authenticated/app/saved'
    | '/_authenticated/app/'
    | '/_authenticated/app/contracts/$id'
    | '/_authenticated/app/landlord/onboarding'
    | '/_authenticated/app/landlord/properties'
    | '/_authenticated/app/property/$id'
    | '/_authenticated/app/tenant/dashboard'
    | '/_authenticated/app/landlord/properties/$id'
    | '/_authenticated/app/landlord/properties/new'
    | '/_authenticated/app/landlord/units/$id'
    | '/_authenticated/app/landlord/properties/$id/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LandlordsRoute: typeof LandlordsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  TenantsRoute: typeof TenantsRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlords': {
      id: '/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof LandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/saved': {
      id: '/_authenticated/app/saved'
      path: '/app/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AuthenticatedAppSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/requests': {
      id: '/_authenticated/app/requests'
      path: '/app/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AuthenticatedAppRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/app/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/app/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/landlord': {
      id: '/_authenticated/app/landlord'
      path: '/app/landlord'
      fullPath: '/app/landlord'
      preLoaderRoute: typeof AuthenticatedAppLandlordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/explore': {
      id: '/_authenticated/app/explore'
      path: '/app/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AuthenticatedAppExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/contracts': {
      id: '/_authenticated/app/contracts'
      path: '/app/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AuthenticatedAppContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/become-landlord': {
      id: '/_authenticated/app/become-landlord'
      path: '/app/become-landlord'
      fullPath: '/app/become-landlord'
      preLoaderRoute: typeof AuthenticatedAppBecomeLandlordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/tenant/dashboard': {
      id: '/_authenticated/app/tenant/dashboard'
      path: '/app/tenant/dashboard'
      fullPath: '/app/tenant/dashboard'
      preLoaderRoute: typeof AuthenticatedAppTenantDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/property/$id': {
      id: '/_authenticated/app/property/$id'
      path: '/app/property/$id'
      fullPath: '/app/property/$id'
      preLoaderRoute: typeof AuthenticatedAppPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/landlord/properties': {
      id: '/_authenticated/app/landlord/properties'
      path: '/properties'
      fullPath: '/app/landlord/properties'
      preLoaderRoute: typeof AuthenticatedAppLandlordPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppLandlordRoute
    }
    '/_authenticated/app/landlord/onboarding': {
      id: '/_authenticated/app/landlord/onboarding'
      path: '/onboarding'
      fullPath: '/app/landlord/onboarding'
      preLoaderRoute: typeof AuthenticatedAppLandlordOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppLandlordRoute
    }
    '/_authenticated/app/contracts/$id': {
      id: '/_authenticated/app/contracts/$id'
      path: '/$id'
      fullPath: '/app/contracts/$id'
      preLoaderRoute: typeof AuthenticatedAppContractsIdRouteImport
      parentRoute: typeof AuthenticatedAppContractsRoute
    }
    '/_authenticated/app/landlord/units/$id': {
      id: '/_authenticated/app/landlord/units/$id'
      path: '/units/$id'
      fullPath: '/app/landlord/units/$id'
      preLoaderRoute: typeof AuthenticatedAppLandlordUnitsIdRouteImport
      parentRoute: typeof AuthenticatedAppLandlordRoute
    }
    '/_authenticated/app/landlord/properties/new': {
      id: '/_authenticated/app/landlord/properties/new'
      path: '/new'
      fullPath: '/app/landlord/properties/new'
      preLoaderRoute: typeof AuthenticatedAppLandlordPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedAppLandlordPropertiesRoute
    }
    '/_authenticated/app/landlord/properties/$id': {
      id: '/_authenticated/app/landlord/properties/$id'
      path: '/$id'
      fullPath: '/app/landlord/properties/$id'
      preLoaderRoute: typeof AuthenticatedAppLandlordPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedAppLandlordPropertiesRoute
    }
    '/_authenticated/app/landlord/properties/$id/units': {
      id: '/_authenticated/app/landlord/properties/$id/units'
      path: '/units'
      fullPath: '/app/landlord/properties/$id/units'
      preLoaderRoute: typeof AuthenticatedAppLandlordPropertiesIdUnitsRouteImport
      parentRoute: typeof AuthenticatedAppLandlordPropertiesIdRoute
    }
  }
}

interface AuthenticatedAppContractsRouteChildren {
  AuthenticatedAppContractsIdRoute: typeof AuthenticatedAppContractsIdRoute
}

const AuthenticatedAppContractsRouteChildren: AuthenticatedAppContractsRouteChildren =
  {
    AuthenticatedAppContractsIdRoute: AuthenticatedAppContractsIdRoute,
  }

const AuthenticatedAppContractsRouteWithChildren =
  AuthenticatedAppContractsRoute._addFileChildren(
    AuthenticatedAppContractsRouteChildren,
  )

interface AuthenticatedAppLandlordPropertiesIdRouteChildren {
  AuthenticatedAppLandlordPropertiesIdUnitsRoute: typeof AuthenticatedAppLandlordPropertiesIdUnitsRoute
}

const AuthenticatedAppLandlordPropertiesIdRouteChildren: AuthenticatedAppLandlordPropertiesIdRouteChildren =
  {
    AuthenticatedAppLandlordPropertiesIdUnitsRoute:
      AuthenticatedAppLandlordPropertiesIdUnitsRoute,
  }

const AuthenticatedAppLandlordPropertiesIdRouteWithChildren =
  AuthenticatedAppLandlordPropertiesIdRoute._addFileChildren(
    AuthenticatedAppLandlordPropertiesIdRouteChildren,
  )

interface AuthenticatedAppLandlordPropertiesRouteChildren {
  AuthenticatedAppLandlordPropertiesIdRoute: typeof AuthenticatedAppLandlordPropertiesIdRouteWithChildren
  AuthenticatedAppLandlordPropertiesNewRoute: typeof AuthenticatedAppLandlordPropertiesNewRoute
}

const AuthenticatedAppLandlordPropertiesRouteChildren: AuthenticatedAppLandlordPropertiesRouteChildren =
  {
    AuthenticatedAppLandlordPropertiesIdRoute:
      AuthenticatedAppLandlordPropertiesIdRouteWithChildren,
    AuthenticatedAppLandlordPropertiesNewRoute:
      AuthenticatedAppLandlordPropertiesNewRoute,
  }

const AuthenticatedAppLandlordPropertiesRouteWithChildren =
  AuthenticatedAppLandlordPropertiesRoute._addFileChildren(
    AuthenticatedAppLandlordPropertiesRouteChildren,
  )

interface AuthenticatedAppLandlordRouteChildren {
  AuthenticatedAppLandlordOnboardingRoute: typeof AuthenticatedAppLandlordOnboardingRoute
  AuthenticatedAppLandlordPropertiesRoute: typeof AuthenticatedAppLandlordPropertiesRouteWithChildren
  AuthenticatedAppLandlordUnitsIdRoute: typeof AuthenticatedAppLandlordUnitsIdRoute
}

const AuthenticatedAppLandlordRouteChildren: AuthenticatedAppLandlordRouteChildren =
  {
    AuthenticatedAppLandlordOnboardingRoute:
      AuthenticatedAppLandlordOnboardingRoute,
    AuthenticatedAppLandlordPropertiesRoute:
      AuthenticatedAppLandlordPropertiesRouteWithChildren,
    AuthenticatedAppLandlordUnitsIdRoute: AuthenticatedAppLandlordUnitsIdRoute,
  }

const AuthenticatedAppLandlordRouteWithChildren =
  AuthenticatedAppLandlordRoute._addFileChildren(
    AuthenticatedAppLandlordRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppBecomeLandlordRoute: typeof AuthenticatedAppBecomeLandlordRoute
  AuthenticatedAppContractsRoute: typeof AuthenticatedAppContractsRouteWithChildren
  AuthenticatedAppExploreRoute: typeof AuthenticatedAppExploreRoute
  AuthenticatedAppLandlordRoute: typeof AuthenticatedAppLandlordRouteWithChildren
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRequestsRoute: typeof AuthenticatedAppRequestsRoute
  AuthenticatedAppSavedRoute: typeof AuthenticatedAppSavedRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPropertyIdRoute: typeof AuthenticatedAppPropertyIdRoute
  AuthenticatedAppTenantDashboardRoute: typeof AuthenticatedAppTenantDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppBecomeLandlordRoute: AuthenticatedAppBecomeLandlordRoute,
  AuthenticatedAppContractsRoute: AuthenticatedAppContractsRouteWithChildren,
  AuthenticatedAppExploreRoute: AuthenticatedAppExploreRoute,
  AuthenticatedAppLandlordRoute: AuthenticatedAppLandlordRouteWithChildren,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRequestsRoute: AuthenticatedAppRequestsRoute,
  AuthenticatedAppSavedRoute: AuthenticatedAppSavedRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPropertyIdRoute: AuthenticatedAppPropertyIdRoute,
  AuthenticatedAppTenantDashboardRoute: AuthenticatedAppTenantDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LandlordsRoute: LandlordsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  TenantsRoute: TenantsRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
